from common import ArgParser
from text_helper import *
import time

class TBGenerator:
	def __init__(self, args:ArgParser) -> None:
		self.args = args
		self.text_helper = TextHelper(self.args)

	def tb_gen_top(self):
		self.text_helper.write_file("`timescale 1ns/1ns\n")
		self.text_helper.write_comment("testbench generated by HDL DEALER", level = CmtType.HEAD)

		self.text_helper.write_comment("macro define check", level = CmtType.CHAPTER)
		self.text_helper.write_file(self.text_helper.macro_def_check)